trigger:
  branches:
    include:
      - main  # Trigger the pipeline on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureToolkit'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'internal'  # Use the appropriate feed name

- task: Maven@3
  inputs:
    mavenPomFile: 'finessfitness/ffbackend/ffbackend/pom.xml'  # Path to your Maven POM file
    goals: 'clean install'   # Maven goals to execute
    options: '-DskipTests=true'  # Skip tests during the initial build

- task: Maven@3
  inputs:
    mavenPomFile: 'finessfitness/ffbackend/ffbackend/pom.xml'
    goals: 'test'  # Run tests separately
    options: '-Dmaven.test.failure.ignore=true'  # Ignore test failures for now