trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:

# Frontend
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.1'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm install (frontend)'
  workingDirectory: 'finess-fitness/frontend'

- script: |
    npm run build
  displayName: 'npm run build (frontend)'
  workingDirectory: 'finess-fitness/frontend'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'finess-fitness/frontend/build'
    artifactName: 'frontend-drop'
    publishLocation: 'Container'

# Backend
- task: Maven@3
  inputs:
    mavenPomFile: 'finess-fitness/ffbackend/ffbackend/pom.xml'
    mavenOptions: '-Xmx3072m -XX:+TieredCompilation -XX:TieredStopAtLevel=1'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'clean package'
  env:
    MAVEN_OPTS: '-Xmx4096m'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'finess-fitness/ffbackend/ffbackend/target'
    artifactName: 'backend-drop'
    publishLocation: 'Container'