trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.1'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm install (frontend)'
  workingDirectory: 'finess-fitness/frontend'

- script: |
    npm run build
  displayName: 'npm run build (frontend)'
  workingDirectory: 'finess-fitness/frontend'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'finess-fitness/frontend/build'
    artifactName: 'frontend-drop'
    publishLocation: 'Container'